### ISSUE TITLE
Visualization unit tests break with new matplotlib v3.3.0

### ISSUE THREAD

**Issue by wkirgsn** [upb-lea/gym-electric-motor#78]
See https://travis-ci.org/github/upb-lea/gym-electric-motor/builds/714538399

Unit tests in test_visualization.py break with the new matplotlib version 3.3.0

**Comment by atra94** [comment]
I have seen that you have already constrained the matplotlib version in the requirements.
Therefore, I think we can close this issue because we will need new tests for the refactored visualization (#55) . We will directly test it on the newest matplotlib version. It will be completed till the next merge into the masters branch.

Are you ok with that?

**Comment by wkirgsn** [comment]
sounds legit
